### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by danielbuechele** [ruffythepirate/sql-apply#2]
Currently, it looks like the intended use-case is to be called from node. Could we make this callable via CLI.

Thinking of something like: `npx sql-apply --database postgres://user:password@localhost:5432 --dir ./migrations`

**Comment by ruffythepirate** [comment]
I quite like this idea, that would be awesome. I'll still keep the runMigration function because one of my biggest usecases is to have an easy way to ensure that my integration tests are running against the same schema that my sandbox and production environment is. But if it's easy I'd definitely add a wrapper that makes this callable through npx.

**Comment by ruffythepirate** [comment]
Fixed in 2.1.1
